djangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from rest_framework import routers

router = routers.DefaultRouter()

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [path('', include('ethcrawler.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

ethcrawler/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'ethcrawler'

urlpatterns = [
    url('history', views.check_by_block, name='history'),
    url('balance', views.check_balance, name='balance'),
    url('', views.home, name='home')

]

ethcrawler/models.py
from django.db import models

# Create your models here.

ethcrawler/views.py
import requests
from django.http import HttpResponse
from django.shortcuts import render

import time
import datetime

from django.template import loader


def check_balance(request):
    addr = request.GET['address2']
    t = request.GET['date']
    ts = int(time.mktime(datetime.datetime.strptime(t, "%Y-%m-%d").timetuple()))

    r = requests.get("https://api.etherscan.io/api"
                     "?module=block"
                     "&action=getblocknobytime"
                     "&timestamp=" + str(ts) +
                     "&closest=before"
                     "&apikey=W9FZQXURBZSTXATJTIUGK7QJZPFYRW12N5",
                     headers={"Content-Type": "application/json"}, )
    blockno = r.json()['result']

    r = requests.get("https://api.etherscan.io/api?module=account"
                     "&action=txlist"
                     "&address=" + addr +
                     "&startblock=" + blockno +
                     "&endblock=99999999"
                     "&page=1"
                     "&offset=10"
                     "&sort=asc"
                     "&apikey=W9FZQXURBZSTXATJTIUGK7QJZPFYRW12N5",
                     headers={"Content-Type": "application/json"}, )
    normal_transactions = r.json()['result']

    balance = 0
    for element in normal_transactions:

        if element['from'] == addr:
            balance += int(element['value']) / 1000000000000000000 + (int(element['gasPrice']) / 1000000000000000000) * int(element['gasUsed'])
        elif element['to'] == addr:
            balance -= int(element['value']) / 1000000000000000000 + (int(element['gasPrice']) / 1000000000000000000) * int(element['gasUsed'])

    r = requests.get("https://api.etherscan.io/api"
                     "?module=account"
                     "&action=tokentx"                     
                     "&address="+addr +
                     "&page=1"
                     "&offset=100"
                     "&sort=asc"
                     "&apikey=W9FZQXURBZSTXATJTIUGK7QJZPFYRW12N5",
                     headers={"Content-Type": "application/json"}, )

    ftresponse = r.json()['result']

    r = requests.get("https://api.etherscan.io/api"
                     "?module=account"
                     "&action=tokennfttx"                     
                     "&address="+addr +
                     "&page=1"
                     "&offset=100"
                     "&sort=asc"
                     "&apikey=W9FZQXURBZSTXATJTIUGK7QJZPFYRW12N5",
                     headers={"Content-Type": "application/json"}, )

    nftresponse = r.json()['result']
    #import pdb;pdb.set_trace()
    context = {'balance': balance, 'fttokens': ftresponse, 'nfttokens': nftresponse}
    return render(request, 'ethcrawler/balance.html', context)


def check_by_block(request):
    addr = request.GET['address1']
    blockno = request.GET['block']
    r = requests.get("https://api.etherscan.io/api?module=account"
                     "&action=txlist"
                     "&address=" + addr +
                     "&startblock=" + blockno +
                     "&endblock=99999999"
                     "&page=1"
                     "&offset=10"
                     "&sort=asc"
                     "&apikey=W9FZQXURBZSTXATJTIUGK7QJZPFYRW12N5",
                     headers={"Content-Type": "application/json"}, )
    response = r.json()

    context = {'results': response['result']}
    return render(request, 'ethcrawler/history.html', context)


def home(request):
    return render(request, 'ethcrawler/home.html')

ethcrawler/templates/ethcrawler/balance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Balance</title>
</head>
<body style="display: flex">

    <div>

    <div style="margin-left: 20px;margin-top: 10px;">
        <label style="font-weight: bold">ETH Balance:</label>
        <span>{{balance}}</span>
    </div>
    <table style="width:100%;margin-bottom: 20px;margin-top: 30px;margin-right: 20px;" border="1">
    <thead>
        <tr>
          <th>ERC-20 Token Name</th>
          <th>ERC-20 Token Value</th>
        </tr>
    </thead>
    <tbody>
        {% for token in fttokens %}
         <tr>
          <td style="text-align: center">{{token.tokenName}}</td>
          <td style="text-align: center">{{token.value}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table></div>
    <table style="width:20%;margin-top: 60px;margin-left: 20px" border="1">
    <thead>
        <tr>
        <th>ERC-721 Token ID</th>
        <th>ERC-721 Token Name</th>
        </tr>
    </thead>
    <tbody>
    {% for token in nfttokens %}
        <tr>
          <td style="text-align: center">{{token.tokenID}}</td>
          <td style="text-align: center">{{token.tokenName}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table></div>
</div>
</body>
</html>

ethcrawler/templates/ethcrawler/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
<table style="width:100%" border="1">
    <thead>
        <tr>
          <th>Block number</th>
          <th>From</th>
          <th>To</th>
          <th>Value</th>
          <th>Gas</th>
          <th>Gas used</th>
        </tr>
    </thead>
    <tbody>
        {% for result in results %}
        <tr>
          <td style="text-align: center">{{result.blockNumber}}</td>
          <td style="text-align: center">{{result.from}}</td>
          <td style="text-align: center">{{result.to}}</td>
          <td style="text-align: center">{{result.value}}</td>
          <td style="text-align: center">{{result.gas}}</td>
          <td style="text-align: center">{{result.gasUsed}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table></div>
</body>
</html>

ethcrawler/templates/ethcrawler/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h1>ETH Crawler</h1>
    <br>
 <div>
    <form action="{% url 'ethcrawler:history' %}">
        <div style="margin-bottom: 10px">
            <label>Search Address : </label>
            <input style="margin-left: 20px;" type="text" name="address1"/>
        </div>
        <div>
            <label>Block Number : </label>
            <input style="margin-left: 23px;" type="number" name="block" />
        </div>
        <input style="margin-left: 40px;margin-top: 20px;margin-bottom: 40px" type="submit" value="history"/>

    </form>
     <form action="{% url 'ethcrawler:balance' %}" >
         <div style="margin-bottom: 10px">
            <label>Search Address : </label>
            <input style="margin-left: 20px;" type="text" name="address2" />
        </div>
        <div>
            <label>Date Input : </label>
            <input style="margin-left: 50px;" type="date" name="date" />
        </div>
         <button style="margin-left: 40px;margin-top: 20px" type="submit">balance</button>

    </form>

</div>
</body>
</html>